language: node_js
node_js:
  - '7.6'
  - '7'
  - '8'
  - 'node'
after_script:
  - nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email: false
deploy:
  provider: npm
  email: blbridges96@gmail.com
  api_key:
    secure: pJJ7giDCMu/vqAj9BO4nk/aDEf8wm0OETu/BZ6224sjdZ1tGE2i8usqU+j+OZFSP4atd/zR9DFLKdUWIm3aRtCHU/WcAMmp4xAXM2L9RVbfrCg0T1T6+4TotwbjhOMF4XliOS4Wb65DeIxSrPVVOwvY8ZydtQqxvZmjNiRJ3pkQ8TJcpDH6megzY8ru7YzJpJOI7lIGlKU3CniZfltVFrLcLlq1uFISW5uwK+ielb6+bN/kJj5dGjCIt5rLtDnjyewIvruBAC8edT585bQQx1vo1I6j2d7VztEswJZcVNl9HoeiQIZx1EU2I4pQal+elRGSbLtN5npc4K5gUs3tQ1V4WbqL/1tlWSFPePUy4BRhO0/WnGbF8oyignCUDYsqFsgMQtfNNE46l0laXteiWZHcFnYN1h2culaSat1plWwS9O1LWyLTY+Oe1HN4g0FfFJjXRjB8qDRMUBw38Y1duEQDgDo2mNIlq86DEcAkqnvwZeUwXjLMfekD47k6NY/DVde4SgYcw4FjOYopnny4Qnehl8MJWQUzaqJCce+p8NrlJGHHewVpOf3cGX5cSLvCms1JCyERL1/MK65d0qUIw6oWpJv9FqvRRgXXO4EfKVkSHWwRYAMOdPq/RHRBI0UwNxCbh6kbHbK2V7KrPtBi4QEKnJ2wjJrdNc1/892mN010=
  on:
    tags: true
    repo: bbridges/koa-protobuf
